#!/bin/bash

#https://repo2docker.readthedocs.io/en/latest/config_files.html
set -ex
jupyter notebook --generate-config
jupyter --config-dir
#echo 'c.NotebookApp.tornado_settings = {"websocket_max_message_size": 100 * 1024 * 1024}' >> /home/jovyan/.jupyter/jupyter_notebook_config.py
echo 'c.NotebookApp.tornado_settings = {"websocket_max_message_size": 100 * 1024 * 1024}' >> ~/.jupyter/jupyter_notebook_config.py
exec "$@"
